[package]
name = "template_handlebars"
version = "1.0.0"
authors = ["Alexandru Tiniuc <tiniuc.alexandru@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"
handlebars = { version = "4.2.1", features = ["dir_source"] }
serde_json = "1.0"
