[package]
name = "cookie-auth"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-identity = "0.4.0-beta.8"
env_logger = "0.9.0"
rand = "0.8.4"
