[package]
name = "template-tinytemplate"
version = "2.0.0"
authors = ["Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.9.0"
tinytemplate = "1.1"
actix-web = "4.0.0-beta.21"
serde_json = "1"
