[package]
name = "redis_session"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-session = "0.5.0-beta.7"
actix-redis = "0.10.0-beta.5"
env_logger = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
actix-service = "2.0.2"
actix-http = "3.0.0-beta.19"
rand = "0.8.4"
time = "0.3.7"

[dev-dependencies]
actix-rt = "2.6.0"
actix-test = "0.1.0-beta.11"
