[package]
name = "run-in-thread"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
description = "Run actix-web in separate thread"

[dependencies]
actix-web = "4.0.0-beta.21"
log = "0.4"
env_logger = "0.9.0"
