[package]
name = "middleware-example"
version = "2.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
actix-service = "2"
actix-web = "4.0.0-beta.21"
env_logger = "0.9.0"
futures = "0.3.1"
pin-project = "1.0.10"
